<a href="https://colab.research.google.com/github/wjtopp3/CIS-210/blob/main/CIS_210_Unit_11_Lab_11_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The ***healthy_lifestyle*** dataset contains information on **lifestyle measures such as amount of sunshine, pollution, and happiness levels** for 44 major cities around the world. **Apply agglomerative clustering** to the cities' number of hours of sunshine and happiness levels using both sklearn and SciPy.

- Import the needed packages for agglomerative clustering from sklearn and SciPy.
- Initialize and fit an agglomerative clustering model using sklearn's AgglomerativeClustering() function. Use the user-defined number of clusters and ward linkage.
- Add cluster labels to the healthy dataframe.
- Calculate the distances between all instances using SciPy's pdist() function.
- Convert the distance matrix to a square matrix using SciPy's squareform() function.
- Define a clustering model with ward linkage using SciPy's linkage() function.

Ex: If the input is:

4

the output should be:

   sunshine_hours  happiness_levels  labels

0          1858.0              7.44       3

1          2636.0              7.22       0

2          1884.0              7.29       3

3          1821.0              7.35       3

4          1630.0              7.64       3

First five rows of the linkage matrix from SciPy:

 [[39. 40.  0.  2.]

 [28. 43.  0.  3.]

 [ 7. 18.  0.  2.]

 [ 0.  3.  0.  2.]

 [ 8. 42.  0.  2.]]

In [ ]:
# zyBooks Template
import pandas as pd
import seaborn as sns
import numpy as np

# Import needed sklearn packages
# Your code here

# Import needed scipy packages
# Your code here

# Silence warning
import warnings
warnings.filterwarnings('ignore')


healthy = pd.read_csv('healthy_lifestyle.csv')
healthy = healthy.dropna(subset = ['sunshine_hours', 'happiness_levels'])

# Input the number of clusters
number = int(input())

# Define input features
X = healthy[['sunshine_hours', 'happiness_levels']]

# Use StandardScaler() to standardize input features
scaler = StandardScaler()
X = scaler.fit_transform(X)
X = pd.DataFrame(X, columns=['sunshine_hours', 'happiness_levels'])

# Initialize and fit an agglomerative clustering model using ward linkage in scikit-learn, with a user-defined
# number of clusters
# Your code here

# Add cluster labels to the healthy dataframe
healthy['labels']=# Your code here
print(healthy[['sunshine_hours', 'happiness_levels', 'labels']].head())

# Perform agglomerative clustering using SciPy

# Calculate the distances between all instances
# Your code here

# Convert the distance matrix to a square matrix
# Your code here

# Define a clustering model with ward linkage
clustersHealthyScipy = # Your code here

print('First five rows of the linkage matrix from SciPy:\n', np.round(clustersHealthyScipy[:5, :], 0))

In [ ]:
# zyBooks Solution
import pandas as pd
import seaborn as sns
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering

from scipy.cluster.hierarchy import linkage
from scipy.spatial.distance import squareform, pdist

# Silence warning
import warnings
warnings.filterwarnings('ignore')


healthy = pd.read_csv('healthy_lifestyle.csv')
healthy = healthy.dropna(subset = ['sunshine_hours', 'happiness_levels'])

# Input the number of clusters
number = int(input())

# Define input features
X = healthy[['sunshine_hours', 'happiness_levels']]

# Use StandardScaler() to standardize input features
scaler = StandardScaler()
X = scaler.fit_transform(X)
X = pd.DataFrame(X, columns=['sunshine_hours', 'happiness_levels'])

# Initialize and fit an agglomerative clustering model using ward linkage in scikit-learn, with a user-defined
# number of clusters
clustersHealthySklearn = AgglomerativeClustering(n_clusters=number, linkage='ward')
clustersHealthySklearnFit = clustersHealthySklearn.fit(X)

# Add cluster labels to the healthy dataframe
healthy['labels']=clustersHealthySklearnFit.labels_
print(healthy[['sunshine_hours', 'happiness_levels', 'labels']].head())

# Perform agglomerative clustering using SciPy
# Calculate the distances between all instances
dist_matrix = pdist(X)

# Convert the distance matrix to a square matrix
dist_matrix = squareform(dist_matrix)

# Define a clustering model with ward linkage
clustersHealthyScipy = linkage(dist_matrix, method='ward')

print('First five rows of the linkage matrix from SciPy:\n', np.round(clustersHealthyScipy[:5, :], 0))

In [ ]:
# Claud Solution
import pandas as pd
import numpy as np
from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from scipy.cluster.hierarchy import linkage
from scipy.spatial.distance import pdist, squareform

# Read the dataset
df = pd.read_csv('healthy_lifestyle.csv')

# Get the number of clusters from user input
n_clusters = int(input())

# Select the relevant columns (sunshine hours and happiness levels)
# Adjust column names based on your actual dataset
X = df[['Sunshine hours(City)', 'Happiness levels(Country)']].values

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize and fit agglomerative clustering model using sklearn
agg_clustering = AgglomerativeClustering(
    n_clusters=n_clusters,
    linkage='ward'
)

# Fit the model and get cluster labels
labels = agg_clustering.fit_predict(X_scaled)

# Create a dataframe with the results
healthy = pd.DataFrame({
    'sunshine_hours': df['Sunshine hours(City)'],
    'happiness_levels': df['Happiness levels(Country)'],
    'labels': labels
})

# Print the dataframe with cluster labels
print(healthy.head())

# Calculate distances between all instances using SciPy's pdist
distances = pdist(X_scaled, metric='euclidean')

# Convert to square matrix
distance_matrix = squareform(distances)

# Define clustering model with ward linkage using SciPy's linkage
linkage_matrix = linkage(X_scaled, method='ward')

# Print first five rows of the linkage matrix
print("First five rows of the linkage matrix from SciPy:")
print(f" {linkage_matrix[:5]}")